name: Automatic Deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run a one-line script
        run: echo Start deploying Thieng App
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
